### ISSUE TITLE
Couldn't match type 'COff' with 'Int64' When build using GHCJS

### ISSUE THREAD

**Issue by Rizary** [haskell/unix#124] opened 2019-01-09 14:55 UTC
When I try to build project using ghcjs, I got the following error:

```
[15 of 39] Compiling System.Posix.Files.Common ( dist/build/System/Posix/Files/Common.hs, dist/build/System/Posix/Files/Common.js_o )

System/Posix/Files/Common.hsc:523:51: error:
    • Couldn't match type ‘COff’ with ‘Int64’
      Expected type: Int64
        Actual type: FileOffset
    • In the second argument of ‘c_ftruncate’, namely ‘off’
      In the second argument of ‘throwErrnoIfMinus1_’, namely
        ‘(c_ftruncate fd off)’
      In the expression:
        throwErrnoIfMinus1_ "setFdSize" (c_ftruncate fd off)
    |
523 |   throwErrnoIfMinus1_ "setFdSize" (c_ftruncate fd off)
    |                                                   ^^^
cabal: Failed to build unix-2.7.2.2 (which is required by exe:matrix-ui from
matrix-ui-0.3.0.0).
```

OS: Ubuntu
GHCJS: 8.2
Cabal: Head

https://github.com/haskell/unix/blob/8d188ed8067af17dfcc2cd6cbbfda7294ba17e17/System/Posix/Files/Common.hsc#L523

**Comment by hvr** [comment] 2019-01-09 22:42
Duplicate of #111

**Closed** 2019-01-09 22:43 UTC
